version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - GRANT_SUDO=1
    tty: true
